export const categoryCompletionIds = [
  "dados-mentirosos-perudo",
  "farkle-diez-mil",
  "dados-zombie",
  "liar-s-dice-estilo-casino",
  "craps-dados-de-casino",
  "sichuan-dice",
  "crown-and-anchor",
  "pig-el-cerdo",
  "bunco",
  "cee-lo",
  "hazard",
  "el-asesino-de-la-mansion",
  "codigo-de-redes",
  "pistas-abstractas",
  "deduccion-alquimica",
  "adivina-quien",
  "linea-de-tiempo",
  "el-intruso",
  "construccion-de-colchas",
  "la-colmena",
  "ventanas-de-catedral",
  "bloques-geometricos",
  "quoridor",
  "onitama",
  "yinsh",
  "dvonn",
];
export const categoryCompletionMetadata: Record<
  string,
  { ready: boolean; players: string; subtitle?: string }
> = {
  "dados-mentirosos-perudo": { ready: true, players: "2–6 jugadores" },
  "farkle-diez-mil": { ready: true, players: "2–4 jugadores" },
  "dados-zombie": { ready: true, players: "2–4 jugadores" },
  "liar-s-dice-estilo-casino": {
    ready: true,
    players: "2–6 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "craps-dados-de-casino": { ready: true, players: "2–4 jugadores" },
  "sichuan-dice": {
    ready: true,
    players: "2–4 jugadores",
    subtitle:
      "Variante original de cierre de números; no se atribuye un reglamento histórico.",
  },
  "crown-and-anchor": { ready: true, players: "2–4 jugadores" },
  "pig-el-cerdo": { ready: true, players: "2–4 jugadores" },
  bunco: {
    ready: true,
    players: "4 jugadores",
    subtitle: "Bunco de una mesa: cuatro puestos, dos equipos, seis rondas.",
  },
  "cee-lo": { ready: true, players: "2–4 jugadores" },
  hazard: { ready: true, players: "2–4 jugadores" },
  "el-asesino-de-la-mansion": {
    ready: true,
    players: "3–6 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "codigo-de-redes": {
    ready: true,
    players: "4 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "pistas-abstractas": {
    ready: true,
    players: "3–6 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "deduccion-alquimica": {
    ready: true,
    players: "2–4 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "adivina-quien": {
    ready: true,
    players: "1–2 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "linea-de-tiempo": { ready: true, players: "2–6 jugadores" },
  "el-intruso": {
    ready: true,
    players: "3–6 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "construccion-de-colchas": {
    ready: true,
    players: "1–2 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "la-colmena": { ready: true, players: "1–2 jugadores" },
  "ventanas-de-catedral": {
    ready: true,
    players: "2–4 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  "bloques-geometricos": {
    ready: true,
    players: "2–4 jugadores",
    subtitle: "Edición original de Games; reglas de esta variante en la ayuda.",
  },
  quoridor: { ready: true, players: "1–2 jugadores" },
  onitama: { ready: true, players: "1–2 jugadores" },
  yinsh: { ready: true, players: "1–2 jugadores" },
  dvonn: { ready: true, players: "1–2 jugadores" },
};
