// Ideas supplied by Alejandro Pico; these entries are disabled until implemented.
export const roadmapGames = [
  {
    id: "damas-internacionales",
    name: "Damas Internacionales",
    subtitle: "Capturas obligatorias saltando piezas en tableros de 10x10.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "shogi-ajedrez-japones",
    name: "Shogi (Ajedrez Japonés)",
    subtitle:
      "Las piezas capturadas se pueden reintroducir en el campo de juego.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "xiangqi-ajedrez-chino",
    name: "Xiangqi (Ajedrez Chino)",
    subtitle:
      "Piezas con movimientos únicos (como el Cañón) cruzando un río central.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "backgammon",
    name: "Backgammon",
    subtitle:
      "Movimiento de fichas guiado por dados, bloqueos y retornos a la casilla de salida.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "damas-chinas",
    name: "Damas Chinas",
    subtitle:
      "Carrera de salto de piezas sobre un tablero con forma de estrella.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "molino-nine-men-s-morris",
    name: "Molino (Nine Men's Morris)",
    subtitle: "Alinear tres fichas para eliminar una del rival.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "senet",
    name: "Senet",
    subtitle:
      "El juego del antiguo Egipto; una carrera lineal con palos de azar.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "tafl-hnefatafl",
    name: "Tafl (Hnefatafl)",
    subtitle:
      "Ajedrez vikingo asimétrico donde el rey debe escapar de los atacantes.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "juego-de-la-oca",
    name: "Juego de la Oca",
    subtitle: "Azar puro con casillas de penalización y avance automático.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "ur-juego-real-de-ur",
    name: "Ur (Juego Real de Ur)",
    subtitle:
      "Carrera de dados ancestral mesopotámica sobre un tablero con forma de puente.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "pachisi",
    name: "Pachisi",
    subtitle: "El ancestro indio del parchís jugado sobre una cruz de tela.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "chaturanga",
    name: "Chaturanga",
    subtitle: "El predecesor ancestral de la India del ajedrez moderno.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "fanorona",
    name: "Fanorona",
    subtitle:
      "Juego de Madagascar basado en capturas por aproximación y retirada de fichas.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "surakarta",
    name: "Surakarta",
    subtitle:
      "Juego indonesio de capturas mediante movimientos circulares en los extremos.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "bagh-chal-movimiento-de-tigres",
    name: "Bagh Chal (Movimiento de Tigres)",
    subtitle: "Juego nepalí asimétrico de cabras intentando encerrar a tigres.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "mu-torere",
    name: "Mu Torere",
    subtitle:
      "Juego maorí de bloqueo de movimientos en un tablero de estrella de 8 puntas.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "halma",
    name: "Halma",
    subtitle:
      "Juego del siglo XIX precursor de las damas chinas en tablero cuadrado.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "yut-nori",
    name: "Yut Nori",
    subtitle:
      "Juego tradicional coreano de carrera usando bastones de madera como dados.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "patolli",
    name: "Patolli",
    subtitle:
      "Juego prehispánico azteca de apuestas y carreras sobre una cruz.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "nyout",
    name: "Nyout",
    subtitle: "Carrera tradicional centroasiática con dados de madera.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "shax",
    name: "Shax",
    subtitle: "Juego de alineación somalí muy similar al molino.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "tsoro-yematatu",
    name: "Tsoro Yematatu",
    subtitle:
      "Juego de estrategia rápida de Zimbabue en un tablero triangular.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "awale",
    name: "Awalé",
    subtitle:
      "Variante de la familia mancala muy popular en África occidental.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "sugoroku",
    name: "Sugoroku",
    subtitle: "Juego de tablero de carreras japonés similar a la oca.",
    category: "Tradicionales",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sage",
  },
  {
    id: "colonizadores",
    name: "Colonizadores",
    subtitle:
      "Gestión de mano, comercio entre jugadores y construcción de rutas sobre hexágonos.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "tierras-de-losetas",
    name: "Tierras de Losetas",
    subtitle:
      "Colocación de losetas cuadradas y control de zonas (caminos, castillos).",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "rutas-de-vapor",
    name: "Rutas de Vapor",
    subtitle:
      "Recolección de sets de cartas de colores para reclamar conexiones ferroviarias.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "el-mercado-de-joyas",
    name: "El Mercado de Joyas",
    subtitle:
      "Compra de motores de producción (engine building) mediante fichas de recursos.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "la-villa-agricola",
    name: "La Villa Agrícola",
    subtitle:
      "Colocación de trabajadores, gestión de granjas y penalizaciones por falta de comida.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "draft-de-maravillas",
    name: "Draft de Maravillas",
    subtitle:
      "Selección simultánea de cartas que se pasan entre jugadores contiguos.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "isla-de-monstruos",
    name: "Isla de Monstruos",
    subtitle:
      "Lanzamiento y reserva de dados (Yahtzee) para atacar a otros jugadores en una zona central.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "el-gran-bazar",
    name: "El Gran Bazar",
    subtitle:
      "Movimiento de un peón principal con ayudantes que se dejan en casillas de acciones.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "diseno-de-mosaicos",
    name: "Diseño de Mosaicos",
    subtitle:
      "Draft de azulejos de un mercado central para rellenar líneas de un tablero personal.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "observatorio-de-aves",
    name: "Observatorio de Aves",
    subtitle:
      "Construcción de combinaciones de cartas (combos) activadas por hábitats.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "terraformacion-planetaria",
    name: "Terraformación Planetaria",
    subtitle:
      "Gestión de proyectos globales subiendo temperatura, oxígeno y océanos.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "lineas-de-produccion",
    name: "Líneas de Producción",
    subtitle:
      "Conexión de industrias (carbón, hierro) en una red económica interconectada.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "expedicion-arqueologica",
    name: "Expedición Arqueológica",
    subtitle:
      "Combinación de colocación de trabajadores con construcción de mazos de cartas.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "reserva-de-naturaleza",
    name: "Reserva de Naturaleza",
    subtitle:
      "Gestión de un zoo moderno mediante una fila de acciones que varían su potencia según su posición.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "el-laberinto-magico",
    name: "El Laberinto Mágico",
    subtitle:
      "Mover peones sobre un tablero con paredes invisibles inferiores (imanes).",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "subasta-de-propiedades",
    name: "Subasta de Propiedades",
    subtitle:
      "Fase de pujas por casas seguida de una fase de venta por cheques de dinero.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "el-fabricante-de-alfombras",
    name: "El Fabricante de Alfombras",
    subtitle:
      "Movimiento de un peón común y colocación de telas adyacentes para cobrar peaje.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "construccion-de-castillos",
    name: "Construcción de Castillos",
    subtitle:
      "Dados que determinan qué losetas puedes coger de un mercado y dónde colocarlas.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "viaje-en-el-tiempo",
    name: "Viaje en el Tiempo",
    subtitle:
      'Colocación de trabajadores en exotrajes con la opción de pedir recursos a tu "yo del futuro".',
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "invasion-de-clanes",
    name: "Invasión de Clanes",
    subtitle:
      "Control de áreas, batallas con cartas ocultas y puntos por morir con honor en el Ragnarok.",
    category: "Eurogames",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "solitario-spider",
    name: "Solitario Spider",
    subtitle:
      "Ordenar cartas de una o varias barajas por palos completos descendentes.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "solitario-carta-blanca-freecell",
    name: "Solitario Carta Blanca (FreeCell)",
    subtitle:
      "Solitario donde todas las cartas se ven desde el inicio con 4 casillas libres de apoyo.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "poker-texas-hold-em",
    name: "Póker Texas Hold'em",
    subtitle:
      "Apuestas, faroles y combinaciones de 5 cartas usando cartas comunitarias.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "blackjack-21",
    name: "Blackjack (21)",
    subtitle:
      "Sumar 21 puntos o acercarse al máximo sin pasarse contra el crupier.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "chinchon",
    name: "Chinchón",
    subtitle:
      "Agrupar series de cartas del mismo número o escaleras del mismo palo.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "escoba",
    name: "Escoba",
    subtitle:
      "Sumar 15 puntos combinando cartas de la mano con las del tapete para limpiar la mesa.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "tute",
    name: "Tute",
    subtitle:
      'Juego de bazas español donde se cantan "las cuarenta" o "las veinte" con reyes y caballos.',
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "mus",
    name: "Mus",
    subtitle:
      "Juego de faroles, señas y cuatro grandes fases (grandes, chicas, pares y juego).",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "brisca",
    name: "Brisca",
    subtitle:
      "Juego de bazas rápidas donde el palo de triunfo determina qué carta gana.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "cinquillo",
    name: "Cinquillo",
    subtitle:
      "Ir colocando las cartas sobre la mesa en orden ascendente y descendente a partir de los cincos.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "truco-argentino-uruguayo",
    name: "Truco Argentino / Uruguayo",
    subtitle: "Mentiras, envites y señas en partidas rápidas de 3 cartas.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "rummy-continental",
    name: "Rummy / Continental",
    subtitle:
      "Crear series de números idénticos o escaleras bajando las cartas a la mesa.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "bridge",
    name: "Bridge",
    subtitle:
      "Juego de bazas de alta estrategia por parejas con subasta inicial de contratos.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "cribbage",
    name: "Cribbage",
    subtitle:
      "Sumar puntos mediante combinaciones en la mano que se registran en un tablero perforado de madera.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "hearts-corazones",
    name: "Hearts (Corazones)",
    subtitle:
      "Juego de bazas donde debes evitar ganar corazones y la reina de espadas.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "spades-picas",
    name: "Spades (Picas)",
    subtitle:
      "Bazas donde los jugadores predicen cuántas manos ganarán antes de empezar.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "belote",
    name: "Belote",
    subtitle:
      "El juego de cartas nacional francés basado en bazas y declaraciones de puntos.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "durak",
    name: "Durak",
    subtitle:
      "El clásico juego de cartas ruso de ataque y defensa donde el último con cartas pierde.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "euchre",
    name: "Euchre",
    subtitle:
      "Juego de bazas norteamericano con un mazo reducido de 24 cartas y triunfos dinámicos.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "canasta",
    name: "Canasta",
    subtitle:
      "Variación del rummy donde el objetivo es formar grupos de 7 cartas del mismo valor.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "gin-rummy",
    name: "Gin Rummy",
    subtitle:
      "Versión rápida para dos jugadores de emparejar cartas secretas en la mano.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "mau-mau",
    name: "Mau-Mau",
    subtitle:
      "El predecesor tradicional del Uno; descartar por color o número con efectos especiales.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "briscola-chiamata",
    name: "Briscola Chiamata",
    subtitle:
      "Variante italiana del tute para 5 jugadores con un compañero secreto.",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "tarot-frances",
    name: "Tarot Francés",
    subtitle: "Juego de bazas usando la baraja completa de Tarot (78 cartas).",
    category: "Cartas",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "descarte-explosivo",
    name: "Descarte Explosivo",
    subtitle: "Robar cartas a ciegas con desactivaciones y ataques directos.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "mineros-saboteadores",
    name: "Mineros Saboteadores",
    subtitle:
      "Colocación de cartas de túnel para llegar a la meta mientras enemigos ocultos rompen herramientas.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "lobo-aldea",
    name: "Lobo / Aldea",
    subtitle:
      "Roles ocultos informados por fases de noche (acciones secretas) y día (votación por chat).",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "la-resistencia-avalon",
    name: "La Resistencia / Avalón",
    subtitle:
      "Misiones en equipo donde hay traidores infiltrados que votan el éxito o fracaso en secreto.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "futbol-de-mesa-con-cartas",
    name: "Fútbol de Mesa con Cartas",
    subtitle:
      "Simulación de partidos mediante cartas de pases, regates y chutes.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "guerra-de-cartas-de-energia",
    name: "Guerra de Cartas de Energía",
    subtitle:
      'Duelo rápido de criaturas con habilidades donde puedes "robar" el turno del rival.',
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "combates-del-espacio",
    name: "Combates del Espacio",
    subtitle:
      "Compra de naves de un mercado central para atacar los puntos de vida del oponente (Deckbuilding).",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "dominio-de-reino",
    name: "Dominio de Reino",
    subtitle:
      "El padre del deckbuilding; comprar cartas de acción del tablero para optimizar tu propio mazo.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "cartas-suicidas",
    name: "Cartas Suicidas",
    subtitle:
      "Colocación simultánea en filas numéricas; el que pone la carta número 6 se lleva los puntos negativos.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "el-estafador-de-cartas",
    name: "El Estafador de Cartas",
    subtitle:
      "Juego donde está permitido (y es obligatorio) tirar cartas bajo la mesa sin que el guardián te vea.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "duelo-de-cartas-en-la-corte",
    name: "Duelo de Cartas en la Corte",
    subtitle:
      "Mazos de solo 16 cartas; mantener la carta de mayor valor o eliminar a los rivales por deducción.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "comercio-de-alubias",
    name: "Comercio de Alubias",
    subtitle:
      "Negociación forzada de cartas de plantas que no puedes reordenar en tu mano.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "el-ladron-de-guante-blanco",
    name: "El Ladrón de Guante Blanco",
    subtitle:
      "Cooperativo de cartas donde se exploran pisos de un banco esquivando guardias.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "cartas-del-purgatorio",
    name: "Cartas del Purgatorio",
    subtitle:
      "Coleccionar cuatro órganos sanos mientras infectas o destruyes los órganos de tus rivales.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "senores-de-la-guerra",
    name: "Señores de la Guerra",
    subtitle: "Cooperativo de cartas contra un jefe con rutinas automatizadas.",
    category: "Roles ocultos",
    tags: ["Cartas"],
    players: "2–8 jugadores",
    duration: "",
    ready: false,
    color: "rose",
  },
  {
    id: "nonogramas-picross",
    name: "Nonogramas (Picross)",
    subtitle:
      "Colorear celdas guiado por secuencias de números en los ejes para formar un dibujo pixelado.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "mahjong-solitario",
    name: "Mahjong Solitario",
    subtitle:
      "Retirar parejas libres de fichas chinas apiladas tridimensionalmente.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "crucigramas-interactivos",
    name: "Crucigramas Interactivos",
    subtitle:
      "Rellenar cajas de texto entrelazadas a partir de definiciones horizontales y verticales.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "sopa-de-letras-dinamica",
    name: "Sopa de Letras Dinámica",
    subtitle:
      "Selección de palabras arrastrando el ratón/dedo en una sopa de caracteres.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "bloques-deslizantes",
    name: "Bloques Deslizantes",
    subtitle:
      "Liberar un bloque rojo moviendo bloques de madera circundantes en horizontal o vertical.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "torres-de-hanoi",
    name: "Torres de Hanói",
    subtitle:
      "Algoritmo de mover discos de tamaños decrecientes entre tres postes.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "buscaminas-hexagonal",
    name: "Buscaminas Hexagonal",
    subtitle: "Variante del buscaminas en un entorno de celdas de 6 lados.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "puzle-de-tuberias",
    name: "Puzle de Tuberías",
    subtitle:
      "Rotar segmentos de red para conectar un punto de entrada de agua con uno de salida.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "cruces-numericos-kakuro",
    name: "Cruces Numéricos (Kakuro)",
    subtitle:
      "Crucigramas matemáticos donde las pistas indican la suma de los dígitos de las líneas.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "rutas-de-luces-lights-out",
    name: "Rutas de Luces (Lights Out)",
    subtitle:
      "Cuadrícula de botones que conmutan su estado (encendido/apagado) y el de sus vecinos; el objetivo es apagarlos todos.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "puentes-fluviales-hashiwokakero",
    name: "Puentes Fluviales (Hashiwokakero)",
    subtitle:
      "Conectar islas numeradas mediante líneas (puentes) respetando el número máximo de conexiones.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "laberintos-generativos",
    name: "Laberintos Generativos",
    subtitle:
      "Algoritmos de laberintos aleatorios que el jugador debe recorrer a contrarreloj.",
    category: "Lógica",
    tags: ["Puzles"],
    players: "1 jugador",
    duration: "",
    ready: false,
    color: "lavender",
  },
  {
    id: "el-ahorcado",
    name: "El Ahorcado",
    subtitle:
      "Descubrir palabras letra a letra antes de que se completen los fallos del dibujo.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "cruzapalabras",
    name: "CruzaPalabras",
    subtitle:
      "Tableros con multiplicadores de puntos donde se forman palabras entrelazadas con letras puntuadas.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "basta-tutti-frutti",
    name: "Basta / Tutti Frutti",
    subtitle:
      "Formulario multijugador rápido para escribir categorías (Nombre, Color, País) que empiecen por una letra dada.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "adivina-la-palabra",
    name: "Adivina la Palabra",
    subtitle:
      "Intentos limitados para adivinar una palabra secreta recibiendo feedback de letras correctas (verde) o descolocadas (amarillo).",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "cajas-timbiriche-dots-and-boxes",
    name: "Cajas / Timbiriche (Dots and Boxes)",
    subtitle:
      "Unir puntos con líneas por turnos; el que cierre un cuadrado de 4 lados se lo anota.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "gomoku",
    name: "Gomoku",
    subtitle:
      "Alinear cinco piezas consecutivas en un tablero de ajedrez o Go.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "palabras-encadenadas",
    name: "Palabras Encadenadas",
    subtitle:
      "Introducir palabras por turnos que comiencen por la última sílaba de la palabra anterior.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "conecta-5-pente",
    name: "Conecta 5 (Pente)",
    subtitle:
      "Variante del gomoku con capturas de parejas de fichas del rival.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "el-diccionario",
    name: "El Diccionario",
    subtitle:
      "Inventar definiciones falsas para una palabra real desconocida y votar cuál es la verdadera.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "hex",
    name: "Hex",
    subtitle:
      "Conectar tus dos extremos del tablero de celdas romboidales antes de que el rival conecte los suyos.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "sprouts-brotes",
    name: "Sprouts (Brotes)",
    subtitle:
      "Juego matemático de dibujar líneas entre puntos sin que se crucen ni acumulen más de 3 conexiones por punto.",
    category: "Palabras",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "yahtzee-la-generala",
    name: "Yahtzee / La Generala",
    subtitle:
      "Lanzamientos repetidos de 5 dados para obtener manos de póker (Full, Escaleras, Repóker).",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "dados-mentirosos-perudo",
    name: "Dados Mentirosos (Perudo)",
    subtitle:
      "Apostar sobre el número total de dados con cierta cara ocultos bajo los cubiletes de todos los jugadores.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "farkle-diez-mil",
    name: "Farkle (Diez Mil)",
    subtitle:
      "Tentar a la suerte relanzando dados para acumular puntos, arriesgándote a perder el acumulado si sacas una tirada en blanco.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "dados-zombie",
    name: "Dados Zombie",
    subtitle:
      "Dados de tres colores (fácil, medio, difícil) donde coleccionas cerebros y evitas disparos.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "liar-s-dice-estilo-casino",
    name: "Liar’s Dice Estilo Casino",
    subtitle:
      "Apuestas escalonadas sobre el valor de las caras de tus dados individuales.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "craps-dados-de-casino",
    name: "Craps (Dados de Casino)",
    subtitle:
      "Apuestas complejas basadas en la suma de dos dados en el lanzamiento de apertura.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "sichuan-dice",
    name: "Sichuan Dice",
    subtitle:
      "Juego de dados tradicional de eliminación de fichas por tiradas combinadas.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "crown-and-anchor",
    name: "Crown and Anchor",
    subtitle:
      "Juego de dados tradicional británico de marineros usando símbolos (picas, corazones, coronas, anclas).",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "pig-el-cerdo",
    name: "Pig (El Cerdo)",
    subtitle:
      "Juego de un solo dado donde sumas puntos en tu turno; si sacas un 1, pierdes todo lo acumulado en ese turno y pasas el control.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "bunco",
    name: "Bunco",
    subtitle:
      "Juego de dados social por equipos enfocado en conseguir combinaciones triples del número de la ronda actual.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "cee-lo",
    name: "Cee-lo",
    subtitle:
      "Juego de dados callejero basado en combinaciones automáticas (como 4-5-6) o triples.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "hazard",
    name: "Hazard",
    subtitle:
      "El complicado juego medieval inglés ancestro directo de los dados de casino actuales.",
    category: "Dados",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "sand",
  },
  {
    id: "el-asesino-de-la-mansion",
    name: "El Asesino de la Mansión",
    subtitle:
      "Descarte de cartas de Sospechoso, Arma y Habitación mediante sugerencias cruzadas.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "codigo-de-redes",
    name: "Código de Redes",
    subtitle:
      "Tableros de palabras donde los jefes de equipo guían con una palabra y un índice numérico.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "pistas-abstractas",
    name: "Pistas Abstractas",
    subtitle:
      "Selección de ilustraciones ambiguas basándose en frases poéticas o pistas abstractas de los usuarios.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "mastermind",
    name: "Mastermind",
    subtitle:
      "Descubrir un código oculto de colores mediante pivotes de feedback (blanco = color correcto, negro = posición y color correcto).",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "deduccion-alquimica",
    name: "Deducción Alquímica",
    subtitle:
      "Mezcla de ingredientes virtuales para descubrir fórmulas lógicas mediante descarte de signos.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "adivina-quien",
    name: "Adivina Quién",
    subtitle:
      "Filtrar rostros de personajes mediante preguntas binarias (¿Tiene gafas?, ¿Es rubio?).",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "mensajes-cruzados",
    name: "Mensajes Cruzados",
    subtitle:
      "Transmisión de códigos numéricos secretos entre compañeros sin que el equipo rival intercepte el patrón de palabras clave.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "linea-de-tiempo",
    name: "Línea de Tiempo",
    subtitle:
      "Colocar cartas de inventos o eventos históricos en una línea temporal común en la posición correcta.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "el-intruso",
    name: "El Intruso",
    subtitle:
      "Todos los jugadores conocen una localización secreta excepto uno (el espía); se hacen preguntas sutiles para descubrir quién está fingiendo.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "inu",
    name: "Inu",
    subtitle:
      "Juego de deducción tradicional japonés basado en adivinar posiciones ocultas.",
    category: "Deducción",
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "blue",
  },
  {
    id: "construccion-de-colchas",
    name: "Construcción de Colchas",
    subtitle:
      "Tetris para dos jugadores gestionado por un sistema de coste de tiempo y botones de divisa.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "la-colmena",
    name: "La Colmena",
    subtitle:
      "Juego de insectos sin tablero; cada pieza se mueve de forma exclusiva intentando rodear a la abeja reina enemiga.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "ventanas-de-catedral",
    name: "Ventanas de Catedral",
    subtitle:
      "Colocación de dados de colores simulando vidrieras, respetando restricciones de valor y color adyacentes.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "bloques-geometricos",
    name: "Bloques Geométricos",
    subtitle:
      "Colocación de piezas de polióminos en un tablero común tocándose estrictamente solo por las esquinas.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "quarto",
    name: "Quarto",
    subtitle:
      "Colocar piezas en un tablero de 4x4; el rival elige qué pieza juegas tú, y ganas alineando 4 piezas con una característica común (altura, color, forma).",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "quoridor",
    name: "Quoridor",
    subtitle:
      "Mover un peón al extremo opuesto del tablero o colocar vallas de madera para bloquear y desviar el camino del rival.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "santorini",
    name: "Santorini",
    subtitle:
      "Mover constructores en un mapa de 5x5 subiendo niveles de edificios y colocando cúpulas para bloquear alturas.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "onitama",
    name: "Onitama",
    subtitle:
      "Duelo de artes marciales en tablero de 5x5 donde los movimientos disponibles rotan constantemente entre los jugadores usando cartas compartidas.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "yinsh",
    name: "YINSH",
    subtitle:
      "Mover anillos alineando fichas de tu color para retirarlas del tablero.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
  {
    id: "dvonn",
    name: "DVONN",
    subtitle:
      "Juego de apilar piezas para mantenerlas conectadas a los nodos de energía centrales del tablero.",
    category: "Abstractos",
    tags: ["Estrategia"],
    players: "1–4 jugadores",
    duration: "",
    ready: false,
    color: "mint",
  },
] as const;
